# Generated by Django 3.2.7 on 2021-09-08 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaten',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naam_certificaat', models.CharField(max_length=100)),
                ('datum_afronding', models.CharField(max_length=50)),
                ('naam_instituut', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contracten',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_uren', models.CharField(max_length=100)),
                ('Startdatum', models.CharField(max_length=100)),
                ('Einddatum', models.CharField(max_length=100)),
                ('functie_contract', models.CharField(max_length=100)),
                ('contract', models.CharField(max_length=100)),
                ('salaris', models.CharField(max_length=100)),
                ('vakantie_dagen', models.CharField(max_length=100)),
                ('Onkostenvergoeding', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leaseautos',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kenteken', models.CharField(max_length=100)),
                ('start_datum_lease_auto', models.CharField(max_length=50)),
                ('merk_auto', models.CharField(max_length=50)),
                ('type_auto', models.CharField(max_length=100)),
                ('leasemaatschappij', models.CharField(max_length=100)),
                ('kilometer_per_jaar', models.CharField(max_length=100)),
                ('lease_bedrag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medewerkers',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=100)),
                ('tussenvoegsel', models.CharField(max_length=6)),
                ('huisnummer', models.CharField(max_length=20)),
                ('straat', models.CharField(max_length=150)),
                ('woonplaats', models.CharField(max_length=150)),
                ('postcode', models.CharField(max_length=10)),
                ('mobielnummer', models.CharField(max_length=20)),
                ('icenummer', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('teriefindicatie', models.FloatField(max_length=20)),
                ('zzper_eigenwerknemer', models.CharField(max_length=50)),
                ('opleidings_niveau', models.CharField(max_length=50)),
                ('godsdienst', models.CharField(max_length=50)),
                ('burgerlijkse_staat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opmerkingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_opmerkingen', models.CharField(default=None, max_length=500)),
                ('opmerkingveld', models.CharField(max_length=500)),
                ('medewerkers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.medewerkers')),
            ],
        ),
    ]
