# Generated by Django 3.2.7 on 2021-09-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opmerkingen',
            name='datum_opmerkingen',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='opmerkingveld',
        ),
    ]
