# Generated by Django 3.2.7 on 2021-09-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20210908_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificaten',
        ),
        migrations.DeleteModel(
            name='Contracten',
        ),
        migrations.DeleteModel(
            name='Leaseautos',
        ),
        migrations.DeleteModel(
            name='Opmerkingen',
        ),
    ]
