# Generated by Django 3.2.7 on 2021-09-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_auto_20210908_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medewerkers',
        ),
    ]
