# Generated by Django 3.2.7 on 2021-09-08 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project1', '0004_delete_medewerkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medewerkers',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voornaam', models.CharField(max_length=100)),
                ('tussenvoegsel', models.CharField(max_length=6)),
                ('huisnummer', models.CharField(max_length=20)),
                ('straat', models.CharField(max_length=150)),
                ('woonplaats', models.CharField(max_length=150)),
                ('postcode', models.CharField(max_length=10)),
                ('mobielnummer', models.CharField(max_length=20)),
                ('icenummer', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=150)),
                ('teriefindicatie', models.FloatField(max_length=20)),
                ('zzper_eigenwerknemer', models.CharField(max_length=50)),
                ('opleidings_niveau', models.CharField(max_length=50)),
                ('godsdienst', models.CharField(max_length=50)),
                ('burgerlijkse_staat', models.CharField(max_length=100)),
            ],
        ),
    ]
