# Generated by Django 3.2.7 on 2021-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_medewerkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerkers',
            name='bnsnummer',
            field=models.IntegerField(null=True),
        ),
    ]
