# Generated by Django 3.2.7 on 2021-09-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0007_medewerkers_geboorte_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaseautos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenteken', models.CharField(max_length=10)),
                ('start_datum_lease_auto', models.DateField(null=True)),
                ('eind_datum_lease_auto', models.DateField(null=True)),
                ('merk_auto', models.CharField(max_length=50)),
                ('type_auto', models.CharField(max_length=100)),
                ('leasemaatschappij', models.CharField(max_length=100)),
                ('kilometer_per_jaar', models.IntegerField(null=True)),
                ('lease_bedrag', models.FloatField(max_length=20)),
            ],
        ),
    ]
