# Generated by Django 3.2.7 on 2021-09-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0008_leaseautos'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseautos',
            name='medewerkers',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project1.medewerkers'),
        ),
    ]
