# Generated by Django 3.2.7 on 2021-09-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0009_leaseautos_medewerkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opmerkingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_opmerkingen', models.DateField(null=True)),
                ('opmerkingveld', models.CharField(max_length=1000)),
                ('medewerkers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project1.medewerkers')),
            ],
        ),
    ]
