# Generated by Django 3.2.7 on 2021-09-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0010_opmerkingen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_uren', models.IntegerField(null=True)),
                ('Startdatum', models.DateField(null=True)),
                ('Einddatum', models.DateField(null=True)),
                ('functie_contract', models.CharField(max_length=100)),
                ('salaris', models.FloatField(max_length=20)),
                ('vakantie_dagen', models.IntegerField(null=True)),
                ('Onkostenvergoeding', models.FloatField(max_length=20)),
                ('medewerkers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project1.medewerkers')),
            ],
        ),
        migrations.CreateModel(
            name='Certificaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_certificaat', models.CharField(max_length=100)),
                ('datum_afronding', models.DateField(null=True)),
                ('accreditatie_nummer', models.CharField(max_length=100)),
                ('naam_instituut', models.CharField(max_length=100)),
                ('medewerkers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project1.medewerkers')),
            ],
        ),
    ]
