# Generated by Django 3.2.7 on 2021-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0011_certificaten_contracten'),
    ]

    operations = [
        migrations.AddField(
            model_name='medewerkers',
            name='achternaam',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
