# Generated by Django 3.2.7 on 2021-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0013_auto_20210914_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medewerkers',
            name='tussenvoegsel',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
