# Generated by Django 3.2.7 on 2021-10-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0015_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
