# Generated by Django 3.2.7 on 2021-10-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0018_rename_post_comment_medewerkers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opmerkingen',
            name='medewerkers',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Opmerkingen',
        ),
    ]
