# Generated by Django 3.2.7 on 2021-10-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0022_opmerkingen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opmerkingen',
            name='datum_opmerkingen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
