# Generated by Django 3.2.7 on 2021-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0027_alter_opmerkingen_datum_opmerkingen'),
    ]

    operations = [
        migrations.AddField(
            model_name='opmerkingen',
            name='naam_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
