# Generated by Django 3.2.15 on 2022-11-28 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0028_opmerkingen_naam_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aanbiedingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aangemaakt_door', models.CharField(blank=True, choices=[('1', 'Yoeri Tromp'), ('2', 'Nicky Slothouwer'), ('3', 'Coen Berkhout jr'), ('4', 'Jessica Berkhout')], max_length=50)),
                ('registratie', models.DateField(blank=True, null=True)),
                ('laatste_update', models.DateField(blank=True, null=True)),
                ('functie', models.CharField(choices=[('1', '.NET Developer'), ('3', ' 3D - tekenaar'), ('4', ' Android Developer '), ('5', ' App Developer'), ('6', 'Applicatie Specialist'), ('7', ' Applicatiebeheerder'), ('8', 'Applicatieontwerper'), ('9', 'Applicatieontwerper'), ('10', 'Applicatieontwikkelaar'), ('11', 'Application Designer'), ('12', 'Assistent filiaalmanager '), ('13', 'Backend Developer'), ('14', 'Beleidsmedewerker Informatiebeveiliging'), ('15', 'Business Analist'), ('16', 'Business Architect '), ('17', 'Citrix Specialist'), ('18', 'Commercieel Directeur'), ('19', 'Content Manager'), ('20', 'Contractmanager '), ('21', 'Data - analist'), ('22', 'Database Administrator'), ('23', 'Directeur ICT'), ('24', 'Directeur IT '), ('25', 'Embedded Engineer'), ('26', 'Filiaalmanager'), ('27', 'Functioneel Beheerder'), ('28', 'Hacker '), ('29', 'Hardware Engineer'), ('30', 'Helpdeskmedewerker'), ('31', ' HTML Specialist'), ('32', 'Applicatieontwerper'), ('33', 'ICT Specialist'), ('34', ' ICT Supportmedewerker'), ('35', 'Informatieanalist'), ('36', 'Informatiemanager'), ('37', 'Infrastructuur Ontwerper'), ('38', ' Infrastructuur Specialist'), ('39', 'iOS Developer'), ('40', 'Architect'), ('41', 'IT Auditor'), ('42', ' IT Trainee'), ('43', 'JAVA Developer'), ('44', 'Junior Pega Developer'), ('45', 'Leraar Informatica'), ('46', ' Management Consultant'), ('47', 'Netwerk Engineer'), ('48', 'Netwerkbeheerder'), ('49', 'Netwerkmanager'), ('50', ' Netwerkspecialist'), ('51', 'Operations Manager'), ('52', 'PHP Developer'), ('53', 'PHP Programmeur'), ('54', ' PLC Engineer'), ('55', 'PLC Programmeur'), ('56', 'Procesmanager'), ('57', 'Processpecialist'), ('58', ' Programmeur'), ('59', 'Projectcontroller'), ('60', 'Projectmanager IT'), ('61', 'ApplicatieSpecialist'), ('62', ' Applicatiebeheerder'), ('63', 'Applicatieontwerper'), ('64', 'Requirements Analist'), ('65', 'Sales Analist'), ('66', ' Sales Manager'), ('67', 'Scrum Master'), ('68', 'SEO specialist'), ('69', 'Service Analist'), ('70', ' Service Co�rdinator'), ('71', 'Servicedesk Medewerker'), ('71', 'Shopmanager'), ('72', 'Software designer'), ('73', ' Software Engineer'), ('74', 'Software tester'), ('75', 'Supportmedewerker'), ('76', 'Systeemarchitect'), ('77', ' Systeembeheerder'), ('78', 'Systeemontwerper'), ('79', 'Systeemontwikkelaar'), ('80', 'Systeemoperator'), ('81', ' Systeemspecialist'), ('82', 'System Engineer'), ('83', 'Technical support engineer'), ('84', 'Technisch adviseur'), ('85', ' Technisch Ontwerper'), ('86', 'Telecom Engineer'), ('87', 'Telecommunicatiemanager'), ('88', 'Test Engineer'), ('89', ' Testanalist'), ('90', 'Testconsultant'), ('91', 'Tester'), ('92', 'Testmanager'), ('93', ' Webdeveloper'), ('94', 'Webmaster'), ('95', 'Servicemanager'), ('96', 'Packager')], max_length=50)),
                ('functie_aanbieding', models.CharField(max_length=50)),
                ('accountmanager', models.CharField(blank=True, choices=[('1', 'Yoeri Tromp'), ('2', 'Nicky Slothouwer'), ('3', 'Coen Berkhout jr'), ('4', 'Jessica Berkhout')], max_length=4)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Intake'), ('3', 'Geplaatst'), ('4', 'Afgewezen'), ('5', 'Opdracht'), ('6', 'Verlopen')], max_length=50)),
                ('tarief', models.FloatField(default=True, max_length=14, null=True)),
                ('betaalkorting', models.FloatField(default=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountmanager', models.CharField(blank=True, choices=[('1', 'Yoeri Tromp'), ('2', 'Nicky Slothouwer'), ('3', 'Coen Berkhout jr'), ('4', 'Jessica Berkhout')], max_length=4)),
                ('broker_naam', models.CharField(blank=True, max_length=50)),
                ('telefoonnummer_broker', models.CharField(blank=True, max_length=20, null=True)),
                ('portaal_broker', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactpersonen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(blank=True, max_length=50)),
                ('mail_adres', models.CharField(blank=True, max_length=50)),
                ('telefoonnummer', models.CharField(blank=True, max_length=30)),
                ('functie', models.CharField(blank=True, max_length=50)),
                ('opmerkingen', models.CharField(blank=True, max_length=300)),
                ('broker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.brokers')),
            ],
        ),
        migrations.CreateModel(
            name='Documenten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_document', models.CharField(blank=True, max_length=20)),
                ('soort_document', models.CharField(blank=True, max_length=50)),
                ('beschrijving', models.CharField(blank=True, max_length=600)),
                ('document', models.FileField(blank=True, null=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Eindklanten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountmanager', models.CharField(blank=True, choices=[('1', 'Yoeri Tromp'), ('2', 'Nicky Slothouwer'), ('3', 'Coen Berkhout jr'), ('4', 'Jessica Berkhout')], max_length=5, null=True)),
                ('klantnaam', models.CharField(blank=True, max_length=50, null=True)),
                ('telefoonnummer_klant', models.CharField(blank=True, max_length=17, null=True)),
                ('portaal_klant', models.URLField(blank=True, max_length=300, null=True)),
                ('contactpersoon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.contactpersonen')),
            ],
        ),
        migrations.CreateModel(
            name='Opdrachten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_opdracht', models.CharField(choices=[('1', 'Lopend'), ('2', 'Afgelopen')], max_length=50)),
                ('startdatum', models.DateField(blank=True, null=True)),
                ('einddatum', models.DateField(blank=True, null=True)),
                ('tarief_opdracht', models.FloatField(blank=True, default=True)),
                ('opdracht_betaalkorting', models.FloatField(blank=True, default=True, null=True)),
                ('aantal_uren', models.IntegerField(blank=True)),
                ('opdracht_aangemaakt_door', models.CharField(blank=True, choices=[('1', 'Yoeri Tromp'), ('2', 'Nicky Slothouwer'), ('3', 'Coen Berkhout jr'), ('4', 'Jessica Berkhout')], max_length=4)),
                ('date_created', models.DateField(blank=True, default='2022-11-28', null=True)),
                ('aanbieding', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.aanbiedingen')),
            ],
        ),
        migrations.CreateModel(
            name='Vestigingplaats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vestiging', models.CharField(blank=True, max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('straatnaam', models.CharField(blank=True, max_length=30)),
                ('huisnummer', models.IntegerField(blank=True)),
                ('plaats', models.CharField(blank=True, max_length=20)),
                ('opmerkingen', models.CharField(blank=True, max_length=300)),
                ('broker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.brokers')),
                ('contactpersoon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.contactpersonen')),
                ('klant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.eindklanten')),
            ],
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='geboorte_datum',
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='godsdienst',
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='mobielnummer',
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='opleidings_niveau',
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='teriefindicatie',
        ),
        migrations.RemoveField(
            model_name='medewerkers',
            name='zzper_eigenwerknemer',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='datum_opmerkingen',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='medewerkers',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='naam_user',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='opmerkingveld',
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='bv',
            field=models.CharField(blank=True, choices=[('1', 'Holding'), ('2', 'Ict'), ('3', 'Infra'), ('4', 'III'), ('5', 'Extern')], max_length=50),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='feedback',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='inhuur',
            field=models.CharField(blank=True, choices=[('1', 'Ja'), ('2', 'Nee')], max_length=50),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='lease_auto',
            field=models.CharField(blank=True, choices=[('1', 'Ja'), ('2', 'All in'), ('3', 'Lease vergoeding'), ('4', 'Geen')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='opleidingsniveau',
            field=models.CharField(blank=True, choices=[('1', 'Middelbaar beroepsonderwijs (MBO)'), ('2', 'Hoger beroepsonderwijs (HBO)'), ('3', 'Wetenschappelijk onderwijs (WO)')], max_length=50),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Intake'), ('2', 'Opdracht'), ('3', 'Leegloop'), ('4', 'Uit dienst')], max_length=50),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='tariefindicatie',
            field=models.FloatField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='medewerkers',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opmerkingen',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opmerkingen',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('MEDEWERKERS', 'MEDEWERKERS'), ('EINDKLANTEN', 'EINDKLANTEN'), ('BROKERS', 'BROKERS')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='opmerkingen',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='opmerkingen',
            name='task_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opmerkingen',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificaten',
            name='medewerkers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project1.medewerkers'),
        ),
        migrations.AlterField(
            model_name='contracten',
            name='medewerkers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project1.medewerkers'),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='achternaam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='bnsnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='burgerlijkse_staat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='icenummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='straat',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='voornaam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medewerkers',
            name='woonplaats',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='Leaseautos',
        ),
        migrations.AddField(
            model_name='eindklanten',
            name='vestiging',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.vestigingplaats'),
        ),
        migrations.AddField(
            model_name='documenten',
            name='medewerker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.medewerkers'),
        ),
        migrations.AddField(
            model_name='contactpersonen',
            name='klant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.eindklanten'),
        ),
        migrations.AddField(
            model_name='contactpersonen',
            name='vestiging',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.vestigingplaats'),
        ),
        migrations.AddField(
            model_name='brokers',
            name='contactpersoon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.contactpersonen'),
        ),
        migrations.AddField(
            model_name='brokers',
            name='vestiging',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.vestigingplaats'),
        ),
        migrations.AddField(
            model_name='aanbiedingen',
            name='broker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.brokers'),
        ),
        migrations.AddField(
            model_name='aanbiedingen',
            name='klant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project1.eindklanten'),
        ),
        migrations.AddField(
            model_name='aanbiedingen',
            name='medewerker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project1.medewerkers'),
        ),
    ]
